In [60]:
import torch
import torch.nn as nn


bilstm = nn.LSTM(5, 6, batch_first=True, bidirectional=True)
bigru = nn.GRU(5, 6, batch_first=True, bidirectional=True)

a = torch.rand(1, 4, 5)
print(a)


tensor([[[0.3298, 0.3625, 0.1212, 0.2040, 0.5032],
         [0.8610, 0.4474, 0.9094, 0.7928, 0.4826],
         [0.2001, 0.0857, 0.4305, 0.3607, 0.6872],
         [0.6043, 0.7604, 0.9408, 0.7212, 0.8564]]])


In [59]:
out, hc = bilstm(a)

print(out.size())
print(out)
print(hc[0])

torch.Size([1, 4, 12])
tensor([[[-0.0078,  0.0714, -0.0735, -0.1729,  0.1023, -0.0378,  0.2358,
           0.0253,  0.2275,  0.0873,  0.0100,  0.2636],
         [-0.1032,  0.0545, -0.0588, -0.2883,  0.0725, -0.0254,  0.1868,
           0.0703,  0.2654,  0.1181,  0.1215,  0.2574],
         [-0.0841,  0.0524, -0.0858, -0.2839,  0.0779, -0.0369,  0.1667,
           0.1148,  0.2083,  0.1086,  0.0718,  0.2128],
         [-0.1397,  0.0181, -0.0351, -0.3435,  0.1163, -0.0752,  0.1458,
           0.0508,  0.1450,  0.0467,  0.0643,  0.1438]]],
       grad_fn=<TransposeBackward0>)
tensor([[[-0.1397,  0.0181, -0.0351, -0.3435,  0.1163, -0.0752]],

        [[ 0.2358,  0.0253,  0.2275,  0.0873,  0.0100,  0.2636]]],
       grad_fn=<StackBackward>)
